import Foundation

/// Fixed-slot transport dispatch. The receiver filters dummies before ledger
/// processing. This does not conceal plaintext from that receiver or hide
/// authentication headers, response timing, other requests, or app lifecycle.
public actor CoverTrafficAdapter {
    public static let envelopeBytes = 32768
    public typealias Transport = @Sendable (Data) async throws -> Data
    private struct Pending {
        let id: UUID
        let bytes: Data
        let continuation: CheckedContinuation<Data, Error>
    }
    private let interval: UInt64
    private let transport: Transport
    private var pending: [Pending] = []
    private var schedule: Task<Void, Never>?
    public private(set) var coverFailures = 0

    public init(ratePerMinute: Double = 10, transport: @escaping Transport) throws {
        guard ratePerMinute.isFinite, ratePerMinute >= 0.01, ratePerMinute <= 600 else {
            throw ShywareError.invalidManifest("cover_traffic_rate must be between 0.01 and 600")
        }
        interval = UInt64(60_000_000_000 / ratePerMinute)
        self.transport = transport
    }

    public static func encode(kind: String, body: Data) throws -> Data {
        guard ["dummy", "cast", "update"].contains(kind) else { throw ShywareError.invalidInput("Invalid dispatch kind") }
        let value = try JSONSerialization.jsonObject(with: body)
        var bytes = try JSONSerialization.data(withJSONObject: ["version": 1, "kind": kind, "body": value], options: [.sortedKeys])
        guard bytes.count <= envelopeBytes else { throw ShywareError.invalidInput("Dispatch body exceeds fixed envelope size") }
        bytes.append(Data(repeating: 32, count: envelopeBytes - bytes.count))
        return bytes
    }

    public func start() {
        guard schedule == nil else { return }
        let interval = self.interval
        schedule = Task { [weak self] in
            while !Task.isCancelled {
                do { try await Task.sleep(nanoseconds: interval) } catch { return }
                guard !Task.isCancelled else { return }
                Task { [weak self] in await self?.tick() }
            }
        }
    }

    public func submit(kind: String, body: Data) async throws -> Data {
        guard schedule != nil else { throw ShywareError.apiError("Cover traffic is not running") }
        guard kind != "dummy" else { throw ShywareError.invalidInput("Dummies are generated by scheduled slots") }
        guard pending.count < 64 else { throw ShywareError.apiError("Cover traffic queue is full") }
        let bytes = try Self.encode(kind: kind, body: body)
        let id = UUID()
        return try await withTaskCancellationHandler(operation: {
            try Task.checkCancellation()
            return try await withCheckedThrowingContinuation { continuation in
                pending.append(Pending(id: id, bytes: bytes, continuation: continuation))
            }
        }, onCancel: { Task { await self.cancel(id) } })
    }

    private func cancel(_ id: UUID) {
        guard let index = pending.firstIndex(where: { $0.id == id }) else { return }
        pending.remove(at: index).continuation.resume(throwing: CancellationError())
    }

    /// A scheduled slot. Exposed internally for deterministic transport tests.
    func tick() async {
        guard schedule != nil else { return }
        let next = pending.isEmpty ? nil : pending.removeFirst()
        do {
            let bytes = try next?.bytes ?? Self.encode(kind: "dummy", body: Data(#"{"tx":""}"#.utf8))
            let result = try await transport(bytes)
            next?.continuation.resume(returning: result)
        } catch {
            if let next { next.continuation.resume(throwing: error) }
            else { coverFailures += 1 }
        }
    }

    public func stop() {
        schedule?.cancel()
        schedule = nil
        for request in pending { request.continuation.resume(throwing: ShywareError.apiError("Cover traffic stopped before dispatch")) }
        pending.removeAll()
        // In-flight writes keep their outcome; uncertain writes are not retried.
    }

    deinit { schedule?.cancel() }
}
